routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome2');
})->name('home');*/
Route::group(['namespace' => 'Front'], function (){
    Route::get('/', 'TournamentController@main')->name('home');
    Route::post('/accept/{id}', 'TournamentController@acceptTournament')->name('acceptTournament');
    Route::get('/forallgamesfront', 'TournamentController@allgamesJson')->name('allgames');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'MainController@index')->name('admin.index');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/tags', 'TagController');
    Route::resource('/posts', 'PostController');
    Route::resource('/tournaments', 'TournamentController');
    Route::get('/allpoints', 'TournamentController@allgamesJson')->name('tournament.allgames');
});

Route::group(['middleware' => 'guest'], function (){
    Route::get('/register', 'UserController@create')->name('register.create');
    Route::post('/register', 'UserController@store')->name('register.store');

    Route::get('/login', 'UserController@loginForm')->name('login.create');
    Route::post('/login', 'UserController@login')->name('login.store');

    Route::get('login/facebook', 'UserController@redirectToProvider')->name('login.facebook');
    Route::get('login/facebook/callback', 'UserController@handleProviderCallback');
});

Route::get('/logout', 'UserController@logout')->name('logout')->middleware('auth');

Route::get('/send', 'ContactController@sendEmail')->name('send.email');

Route::post('/logintotelegram/{id}', 'UserController@loginToTelegram')->name('sendlogin.telega');

Route::post("webhooks/telegram/1435262695:AAEI_W2pLAaXDqnegj4LQi9uAJAziK4qxvs",
    ['as' => 'telegram.webhook', 'uses' => 'TelegramController@process']);

Route::get('/webhook', 'TelegramController@webhook');

app/Tournament.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Tournament extends Model
{

    use Notifiable;

    protected $fillable = [
        'title', 'destination', 'user_id', 'Lat', 'Lng', 'start_game', 'how_many_peoples'
    ];

    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function users(){
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Admin/TournamentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\TestMail;
use App\Notice;
use App\Tournament;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Notifications\Notifiable;
use App\Notifications\LocateTelegram;
use App\Notifications\TelegramNotification;
use Ramsey\Uuid\Uuid;

class TournamentController extends Controller
{
    use Notifiable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tournaments = Tournament::all();
        return view('admin.tournaments.index', compact('tournaments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tournaments = Tournament::all();
        $players = User::where('is_admin', 0)->get();
        $user = Auth::user();
        return view('admin.tournaments.create', compact('tournaments', 'user', 'players'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $date_time_now = date("Y-m-d").'T'.date("H:i");
        //dd($date_time_now);

        $request->validate([
            'title' => 'required|max:255',
            'user_id' => 'integer',
            'destination' => 'required|max:255',
            'Lat' => 'required|numeric',
            'Lng' => 'required|numeric',
            /*'tournaments.user' => 'required',*/
            'how_many_peoples' => 'required|integer|min:8|max:20',
            'start_game' => 'required|after_or_equal:'.$date_time_now
        ]);

        $data = $request->all();
        $user = Auth::user();



        $tournament = Tournament::make($data);

        if ($request->players){
            $massive_players = $request->players;
            if (count($massive_players) > $tournament->how_many_peoples){
                session()->flash('error', 'Вы выбрали недопустимое количество игроков');
                $vasia = session()->all();
                return back()->withInput()->with('error', $vasia['error']);
            }
        }

        $tournament->save();

        $tournament->users()->sync($request->players);

        /* Для отправки писем*/

        $players_for_tournament = $tournament->users;

        $this->sendMailForTournament($players_for_tournament, $tournament);

        $notice = new Notice([
            'id' => Uuid::uuid4()->toString(),
            'notice' => 'Вы приглашены принять участие в турнире по футболу',
            'noticedes' => "Который будет проходить в " .$tournament->destination. " Время и дата - ".$tournament->start_game,
            'noticelink' => 'https://champion.loc',
            'telegramid' => '581654009' // мой ID //Руслана 387200612
        ]);

        $notice->save();
        $notice->notify(new LocateTelegram());
        $notice->notify(new TelegramNotification());


        /*Закончили писать для отправки писем*/

        return redirect()->route('tournaments.index')->with('success', 'Игра по футболу создана');

    }

    public function sendMailForTournament($players_for_tournament, $tournament){
        foreach ($players_for_tournament as $onePlayer){
            Mail::to($onePlayer->email)->send(new TestMail($tournament));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function allgamesJson(){
        $tournaments = Tournament::all();
        return json_encode($tournaments, JSON_UNESCAPED_UNICODE);
    }
}

app/Http/Controllers/Front/TournamentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Tournament;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TournamentController extends Controller
{
    public function main(){
        $user = Auth::user();

        $tournaments = Tournament::with('users')->get();

        if ($user) {
            return view('welcome2', compact('tournaments', 'user'));
        }

        return view('welcome2', compact('tournaments'));
    }

    public function acceptTournament($tournament){

        $user = Auth::check(); //Проверяем, есть ли Юзер
        //Находим нужный турнамент
        $findTournament = Tournament::find($tournament)->load('users');

        if($user){
            $user = Auth::user()->load('tournaments');

            //Есть ли уже у этого пользователя турниры, в которых он уже учавствует
            if ($user->tournaments()->count()){
                foreach ($user->tournaments as $userTournaments){
                    //dump($userTournaments->pivot->tournament_id);
                    if ($userTournaments->pivot->tournament_id == $findTournament->id){
                        return back()->with('success', 'Вы уже учавствуете в соревновании');
                    }
                }
            }

            //dd($user, $findTournament->id);


            //У пользователя нет турниров, и он принимает участие

            $user->tournaments()->syncWithoutDetaching($findTournament);
            return back()->with('success', 'Вы успешно учавствуете в игре');
        }

        //Для незарегистрированных пользователей
        else{
            return back()->with('success', 'Чтобы принять участие, Вам нужно авторизоваться');
        }

    }

    public function allgamesJson(){
        $tournaments = Tournament::all();
        return json_encode($tournaments, JSON_UNESCAPED_UNICODE);
    }
}

resources/views/admin/tournaments/create.blade.php
@extends('admin.layouts.layout')

@section('content')
    <!-- Content Header (Page header) -->

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Новая игра</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Новая игра по футболу</h3>
                        </div>
                        <!-- /.card-header -->

                        <form role="form" method="post" action="{{ route('tournaments.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="title">Название</label>
                                    <input type="text" name="title" value="{{old('title')}}"
                                           class="form-control @error('title') is-invalid @enderror" id="title"
                                           placeholder="Например, игра по футболу 5на5 - 3-и команды">
                                </div>

                                <div class="form-group">
                                    <label for="destination">Где будет проходить игра</label>
                                    <textarea name="destination" class="form-control @error('destination') is-invalid @enderror" id="destination" rows="3" placeholder="Место встречи...">{{isset($tournament->destination) ? $tournament->destination  : old('destination')}}</textarea>
                                </div>

                                <div class="form-group row">
                                    <label for="start_game" class="col-4 col-form-label">Начало игры</label>
                                    <div class="col-8">
                                        <input class="form-control" type="datetime-local" value="{{date("Y-m-d").'T'.date("H:i")}}" id="example-datetime-local-input" name="start_game">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="user_id">Организатор турнира</label>
                                    <select class="form-control custom-select @error('user_id') is-invalid @enderror" id="user_id" name="user_id">
                                        <option name="user_id" value="{{ $user->id }}">{{ $user->name }}</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="LatLng">Выберите на карте, где будет проходить соревнование</label>
                                    <div id="mapid"></div>
                                    <input type="hidden" id="Lng" name="Lng">
                                    <input type="hidden" id="Lat" name="Lat">
                                </div>

                                <div class="form-group">
                                    <label>Добавьте игроков</label>
                                    <div class="select2-purple">
                                        <select name="players[]" id="players" class="select2" multiple="multiple" data-placeholder="Выберите игроков"
                                                data-dropdown-css-class="select2-purple" style="width: 100%;">
                                            @foreach ($players as $k => $player)
                                                <option value="{{$player->id}}">{{$player->name}}</option>
                                            @endforeach

                                        </select>

                                    </div>
                                </div>
                                <!-- /.form-group -->

                                <div class="form-group">
                                    <label for="how_many_peoples">Какое максимальное количество игроков может принимать участие в игре? (Минимум 8 человек - максимум 20</label>
                                    <br>
                                    <input type="number" id="how_many_peoples" name="how_many_peoples" value="8"
                                           min="8" max="20">
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <script>

        var mymap = L.map('mapid').setView([47.91039145, 33.39174271], 16);

        var tileLayer = L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 16,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'pk.eyJ1IjoiZmlyZXdhdGVycyIsImEiOiJja2lrMjN2YnEwNXBoMnNtODhoaTFsZGNlIn0.KHdxZaUaeGjneuxMLMyzxw'
        });
        tileLayer.addTo(mymap);

        mymap.on('click', addMarker); // function по клику

        let newMarker = {};

        // Creating a Marker Options
        let markerOptions = {
            title: "MyLocation",
            clickable: true,
            /*draggable: true*/
        };

        function addMarker(e) {
            //remove previous markers
            console.log(newMarker);
            if (newMarker) {
                mymap.removeLayer(newMarker);
            }
            // Add marker to map at click location; add popup window
            newMarker = new L.marker(e.latlng, markerOptions).bindPopup('Твоя локация').addTo(mymap);
            UpdateLatLng(e);
        }

        function UpdateLatLng(e) {
            let latLngValue;
            latLngValue = e.latlng;
            console.log(latLngValue);
            console.log(e);
            document.getElementById("Lat").value = latLngValue.lat;
            document.getElementById("Lng").value = latLngValue.lng;
            //document.getElementById("destination").value = markerOptions.title;
            //$("#map_lat").val() = latValue;
        }
        /*function UpdateLatLng(e) {
            let latValue, lngValue;
            latValue = e.latlng.lat;
            lngValue = e.latlng.lng;

            console.log(e.latlng);
            document.getElementById("Lat").value = latValue;
            document.getElementById("Lng").value = lngValue;
            document.getElementById("destination").value = markerOptions.title;
            //$("#map_lat").val() = latValue;
        }*/

        /*function UpdateLatLng2(e) {
            let latLngValue = marker.getLatLng();
            latLngValue = position;

            document.getElementById("LatLng").value = latLngValue;
            newMarker.on('dragend', UpdateLatLng2);
            //$("#map_lat").val() = latValue;
        }*/



    </script>
    <!-- /.content -->
@endsection

resources/views/admin/tournaments/index.blade.php
@extends('admin.layouts.layout')

@section('content')
    <!-- Content Header (Page header) -->
    {{--@dd(session()->all())--}}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Игры по футболу</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    {{--@dd(\Illuminate\Support\Facades\Auth::user())--}}
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Список игр</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{{ route('tournaments.create') }}" class="btn btn-primary mb-3">Добавить
                                игру</a>
                            @if (count($tournaments))
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover text-nowrap">
                                        <thead>
                                        <tr>
                                            <th style="width: 30px">#</th>
                                            <th>Наименование</th>
                                            <th>Где будет игра</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($tournaments as $tournament)
                                            <tr>
                                                <td>{{ $tournament->id }}</td>
                                                <td>{{ $tournament->title }}</td>
                                                <td>{{ $tournament->destination }}</td>
                                                <td>
                                                    <a href="{{ route('tournaments.edit', ['tournament' => $tournament->id]) }}"
                                                       class="btn btn-info btn-sm float-left mr-1">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </a>

                                                    <form
                                                        action="{{ route('tournaments.destroy', ['tournament' => $tournament->id]) }}"
                                                        method="post" class="float-left">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger btn-sm"
                                                                onclick="return confirm('Подтвердите удаление')">
                                                            <i
                                                                class="fas fa-trash-alt"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @else
                                <p>Категорий пока нет...</p>
                            @endif
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            @if (!empty(is_array($tournaments)))

                                {{ $tournaments->links() }}
                            @endif

                            {{--<ul class="pagination pagination-sm m-0 float-right">
                                <li class="page-item"><a class="page-link" href="#">«</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">»</a></li>
                            </ul>--}}
                        </div>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection